version: '3.0'
services:
  app:
    image: diffick/nodejs2022q4-service:app
    container_name: app
    build: .
    env_file:
      - .env
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    networks:
      - backbone-network
    volumes:
      - type: bind
        source: ./src
        target: /usr/app/src
    restart: always
    depends_on:
      - db
  db:
    image: diffick/nodejs2022q4-service:db
    container_name: ${POSTGRES_HOST}
    build: ./db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - backbone-network
    restart: always
networks:
  backbone-network:
    driver: bridge
